title        : "SombrAbsol.github.io"
description  : "Site Web de SombrAbsol"
repo         : "SombrAbsol/sombrabsol.github.io"
color        : "#9286ec"
markdown_ext : "markdown,mkdown,mkdn,mkd,md,html"
include      : [".well-known"]

defaults:
  - values:
      layout: "default"
      title: "SombrAbsol"

plugins:
  - "jekyll-github-metadata"

sass:
  sass_dir: _sass
