title        : "SombrAbsol.github.io"
description  : "Site Web de SombrAbsol"
repo         : "SombrAbsol/sombrabsol.github.io"
color        : "#9286ec"
markdown_ext : "markdown,mkdown,mkdn,mkd,md,html"

defaults:
  - scope:
      path: "**/*.md"
    values:
      layout: "default"
      title: "SombrAbsol"

plugins:
  - "jekyll-github-metadata"

collections_dir: pages

sass:
  sass_dir: _sass
  
locale_list: '["en-US", "de-DE", "es-ES", "fr-FR", "it-IT", "ja-JP", "ko-KR"]'

collections:
  en-US:
    output: true
    permalink: /:path:output_ext
  de-DE:
    output: true
  es-ES:
    output: true
  fr-FR:
    output: true
  it-IT:
    output: true
  ja-JP:
    output: true
  ko-KR:
    output: true