title        : "SombrAbsol.github.io"
description  : "Site Web de SombrAbsol"
repo         : "SombrAbsol/sombrabsol.github.io"
color        : "#9286ec"
markdown_ext : "markdown,mkdown,mkdn,mkd,md,html"
include      : [".well-known"]

defaults:
  - values:
      layout: "default"
      title: "SombrAbsol"

plugins:
  - "jekyll-github-metadata"

collections_dir: pages

sass:
  sass_dir: _sass

collections:
  fr-FR:
    output: true
    permalink: /:path:output_ext
  de-DE:
    output: true
  en-US:
    output: true
  es-ES:
    output: true
  it-IT:
    output: true
  ja-JP:
    output: true
  ko-KR:
    output: true
